# 7-fbpod-withsecret.yaml
---
apiVersion: v1
kind: Pod  
metadata:
  name: fb-pod-with-secret
  labels:
    app: fb-app
spec:
  containers: 
  - name: fb-secret-container
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: fb-secret