---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-00337e6deab6507e2
  directoryPerms: "700"
  basePath: "/prod"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "efs-dynamic-sc"
  resources:
    requests:
      storage: 5Gi