#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-pv
spec:
  capacity:
    storage: 5Gi    
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-00337e6deab6507e2 #from EFS DNS