#2_instadeploy_v1.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-deployment #name should be same in other (v2) version of deployment yaml file
  labels:
    app: fb-deploy
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fb-app
      env: prod
  template:
    metadata:
      labels:
        app: fb-app
        env: prod
        version: v1
    spec:
      containers:
      - name: fb-container
        image: dockerhub1105/practicerepo:python_image_v1
        ports:
        - containerPort: 8080