---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fb-pv

spec:

  accessModes:
    - ReadWriteOnce
  capacity: #Size of the EBS volume (20Gi).
    storage: 20Gi

  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0f209f73b770d4c76