---
apiVersion: v1
kind: Pod
metadata:
  name: fb-pod-pv-pvc
  labels:
    app: facebook

spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1f

  containers:
    - name: fb-container
      image: dockerhub1105/practicerepo:http_image_v1
      ports:
        - containerPort: 80

      volumeMounts: #volumeMounts → Specifies where inside the container that storage should be mounted.
        - name: fb-pv
          mountPath: /var/www/html
 
  #volumes → Defines which storage the Pod should use.
  #This Volumes tells Kubernetes:"Attach the Persistent Volume Claim fb-pvc to this Pod."
  #Without volumes, Kubernetes doesn't know which storage to attach to the Pod.
  volumes: 
    - name: fb-pv
      persistentVolumeClaim:
        claimName: fb-pvc

---
apiVersion: v1
kind: Service

metadata:
  name: fb-service

spec:
  type: LoadBalancer

  selector:
    app: facebook

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80